# Change these first
owner: dchtools # Your GitHub organization or username, where this repository lives
repo: uptimemonitor # The name of this repository

sites:
  - name: dch website
    url: https://www.dch.de/home
  - name: nl-api
    url: https://api.djbobo.ch:8081/api2/health
    check: 'status-200'
  - name: djbobo website
    url: https://www.djbobo.ch
  - name: lima-server
    url: https://lima.dch.de:8080/api/v1
    check: 'status-200'
  - name: dchlab
    url: https://lab.dch.de
  - name: pb api
    url: https://api.djbobo.ch/api/health
    check: 'status-200'

status-website:
  baseUrl: /uptimemonitor
  name: dch uptime
  introTitle: "Uptime monitor"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
